### ISSUE TITLE
How to check upload progress in multipart?

### ISSUE THREAD

**Issue by wayne1203** [koush/AndroidAsync#405]
Hello, I'm using the 

//Upload file using Async HTTP Client library

        AsyncHttpClient.getDefaultInstance().executeString(post, new AsyncHttpClient.StringCallback() {
                    @Override
                    public void onCompleted(Exception e, AsyncHttpResponse source, String result) {
                        if (e != null) {
                            e.printStackTrace();
                            // Failed
                            return;
                        }
                       // Success
                    }
                }
        );

But how can I get the progress of the upload?
Thank you.

**Comment by JulienLeal** [comment]
Do you don't have problem with StringCallback type??? See my issue https://github.com/koush/AndroidAsync/issues/410

These have an error with "new StringCallback", because "argument mismatch; cannot be converted to HttpConnectCallback)".
When this issue is resolved, you can override this method onProgress(), like this 
'''
 AsyncHttpClient.getDefaultInstance().execute(post, new StringCallback() {
                @Override
                public void onCompleted(Exception ex, AsyncHttpResponse source, String result) {
                    if (ex != null) {
                                ex.printStackTrace();
                                return;
                            }
                            System.out.println("Server says: " + result);
                        }

                        @Override
                        public void onProgress(AsyncHttpResponse response, long downloaded, long total) {
                            super.onProgress(response, downloaded, total);
                        }
                    });
'''

**Comment by zzxjl1** [comment]
its upload, not download :)
