### ISSUE TITLE
Body null when receiving an array of JSON objects. (AsyncHttpServer post)

### ISSUE THREAD

**Issue by jonasrdm** [koush/AndroidAsync#544]
Hi,

I have a post function as follows:

```
server.post("/mdt/Message/SendMessages", new HttpServerRequestCallback() {
	@Override
	public void onRequest(AsyncHttpServerRequest request, AsyncHttpServerResponse response) {
		JSONObject body = ((JSONObjectBody)request.getBody()).get();
	}
});
```

If I call this function sending a JSON body as : 
`{"prop" : "A"}`
It works.

But if i send an array as, for example :
`[{"prop" : "A"}, {"prop" : "B"}]`
Body is null.

Does anyone knows why it doesn't work with an array of JSON objects?
What can I do?

Thanks!

**Comment by koush** [comment]
Thats a JSON Array, not a JSON Object. They're two different types. Could write your own parser.

**Comment by jonasrdm** [comment]
Thanks for the answer @koush, looking at the source code the `JsonObjectParser `is called on `JsonObjectBody` which is called on `HttpUtil.getBody()`. How can I inject my custom parser on the `AsyncHttpServer`?

I also found the `JsonArrayBody` and `JsonArrayParser`, any suggestions if I could reuse it?

**Comment by koush** [comment]
Eh, unfortunately due to how the type hierarchy of JSONObject and JSONArray works, it's not an easy fix. JSONObject/Array don't share a common ancestor, so there's no parser that returns a superclass variant. Need to parse the entire String once as JSONObject, and if it fails, try JSONArray. Those APIs are kinda shit, which is why I prefer Gson in ion.

**Comment by szabee994** [comment]
Are you planning to resolve this somehow?
